services:
  # Backend API service
  - type: web
    name: contratgenerator-api
    env: node
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: contratgenerator-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: INSEE_KEY
        value: 26O4wu5446dZAb8a_kEPxjf4YVwa
      - key: INSEE_SECRET
        value: WaPMHwRL155vWl2F9NCZ3C4YFkIa

  # Frontend static site
  - type: web
    name: contratgenerator-web
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://contratgenerator-api.onrender.com

databases:
  - name: contratgenerator-db
    databaseName: contratgenerator
    user: contratgenerator
